# Wallpaper daemon config — https://wiki.hyprland.org/Hypr-Ecosystem/hyprpaper/
preload = /home/<user>/.config/hypr/wallpapers/escritorio.jpg
wallpaper = ,/home/<user>/.config/hypr/wallpapers/escritorio.jpg
splash = false
